import Head from 'next/head'
import Image from 'next/image'
import ChartGraph from '../components/Chart/ChartGraph'
import MortageForum from '../components/Forum/MortageForm'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
      <h1>Mortgage Calculator </h1>
      <MortageForum/>
    
     
      </main>

     
    </div>
  )
}
